- name: Installing WebServer
  hosts: all
  remote_user: ec2-user
  become: yes  # Removed quotes around 'yes'
  become_user: root

  tasks:
    - name: Update YUM package cache
      yum:
        update_cache: yes
