pipeline {
    agent any

    environment {
        SERVER_NAME = "your_server_name_here"
        TERRAFORM_ACTION = "apply" // Change this to "destroy" if needed
    }

    stages {
        stage('Checkout') {
            steps {
                script {
                    checkout([$class: 'GitSCM', branches: [[name: 'main']], userRemoteConfigs: [[url: 'https://github.com/Gangulaprathapreddy/DevOps_Project.git']]])
                }
            }
        }

        stage('Terraform Init') {
            steps {
                script {
                    dir('DevOps_Project_2/Terraform') {
                        sh 'terraform init'
                    }
                }
            }
        }

        stage('Terraform Apply/Destroy') {
            steps {
                script {
                    dir('DevOps_Project_2/Terraform') {
                        sh """
                            export TF_VAR_name=${SERVER_NAME}
                            terraform init
                            if [ "$TERRAFORM_ACTION" = "apply" ]; then
                                terraform apply -auto-approve
                            elif [ "$TERRAFORM_ACTION" = "destroy" ]; then
                                terraform destroy -auto-approve
                            else
                                echo "Invalid action provided. Use 'apply' or 'destroy'."
                            fi
                        """
                    }
                }
            }
        }
    }
}

