pipeline {
    agent any

    environment {
        TF_VAR_name = "${SERVER_NAME}"
    }

    stages {
        stage('Checkout') {
            steps {
                script {
                    checkout([$class: 'GitSCM', branches: [[name: 'main']], userRemoteConfigs: [[url: 'https://github.com/Gangulaprathapreddy/DevOps_Project.git']]])
                }
            }
        }

        stage('Terraform Init') {
            steps {
                script {
                    dir('DevOps_Project_2/Terraform') {
                        sh 'terraform init'
                    }
                }
            }
        }

        stage('Terraform Plan') {
            steps {
                script {
                    dir('DevOps_Project_2/Terraform') {
                        sh 'terraform plan -out=tfplan'
                    }
                }
            }
        }

        stage('Terraform Apply') {
            steps {
                script {
                    dir('DevOps_Project_2/Terraform') {
                        sh 'terraform apply -auto-approve tfplan'
                    }
                }
            }
        }
    }

    post {
        always {
            // Clean up or any other post-build tasks
        }
    }
}
